# SPDX-License-Identifier: MIT-0
---
# tasks file for ansible/roles/pihole_setup
- name: Authenticate to Pi-hole API
  ansible.builtin.uri:
    url: "http://localhost:80/api/auth"
    method: POST
    headers:
      Content-Type: "application/json"
    body_format: json
    body:
      password: "{{ pihole_password }}"
    return_content: true
  register: pihole_auth

- name: Add blocklist
  ansible.builtin.uri:
    url: "http://localhost:80/api/lists?type=block"
    method: POST
    headers:
      sid: "{{ pihole_auth.json.session.sid }}"
    body_format: json
    body:
      address:
        - "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/pro.txt"
        - "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/dnsmasq/pro.txt"
        - "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/pro.txt"
        - "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/pro-onlydomains.txt"
        - "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/rpz/pro.txt"
      enabled: true
    status_code: [200, 201]
