#SPDX-License-Identifier: MIT-0
---
# tasks file for ansible/roles/tailscale_installation
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Ensure dependencies are installed
  ansible.builtin.package:
    name:
      - bc
      - curl
      - expect
      - git
      - ca-certificates
    state: present

- name: Download Tailscale's official GPG key
  ansible.builtin.get_url:
    url: "https://pkgs.tailscale.com/stable/{{ version[ansible_distribution + ' ' + ansible_distribution_version] }}"
    dest: /usr/share/keyrings/tailscale-keyring.gpg
    mode: "0644"

- name: Add Tailscale repository to Apt sources
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/tailscale-keyring.gpg] https://pkgs.tailscale.com/stable/{{ ansible_distribution
      | lower }} {{ ansible_distribution_release }} main"
    state: present
    filename: tailscale

- name: Update apt cache after adding Tailscale repository
  ansible.builtin.apt:
    update_cache: true

- name: Install Tailscale
  ansible.builtin.package:
    name: tailscale
    state: present
