# SPDX-License-Identifier: MIT-0
---
# tasks file for ansible/roles/pihole_installation
- name: Check if dnsmasq exists
  ansible.builtin.service_facts:

- name: Create directories for Pi-Hole
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - ~/pihole/etc-pihole
    - ~/pihole/etc-dnsmasq.d

# - name: Disable systemd-resolved
#   ansible.builtin.systemd:
#     name: systemd-resolved
#     state: stopped
#     enabled: false

# - name: Remove resolv.conf symlink
#   ansible.builtin.file:
#     path: /etc/resolv.conf
#     state: absent

# - name: Create static resolv.conf
#   ansible.builtin.copy:
#     dest: /etc/resolv.conf
#     content: |
#       nameserver 1.1.1.1
#       nameserver 8.8.8.8

# - name: Disable dnsmasq if installed
#   ansible.builtin.systemd:
#     name: dnsmasq
#     state: stopped
#     enabled: false
#   when: "'dnsmasq.service' in ansible_facts.services"

- name: Copy docker compose of Pi-Hole
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: ~/pihole/docker-compose.yml
    mode: "0755"
  register: file_copy_result

- name: Run pihole
  community.docker.docker_compose_v2:
    project_src: ~/pihole
    state: present
  register: output
  when: file_copy_result.changed

- name: Show results
  ansible.builtin.debug:
    var: output
  when: file_copy_result.changed
