- name: Install Pi-hole
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      include_role:
        name: docker_installation

    - name: Install Tailscale
      include_role:
        name: tailscale_installation
