---
- name: Install Pi-hole
  hosts: all
  become: true
  # vars_files:
  #   - ./inventory/group_vars/all/vault.yml
  gather_facts: true
  roles:
    - docker_installation
    - tailscale_installation
    - pihole_installation
