---
# Purpose: bring the instance to the desired state by running the role under test.
# Molecule calls this playbook with `molecule converge`.
- name: Converge
  hosts: all
  become: true
  gather_facts: true # Disable if your role does not rely on facts
  # tasks:
  #   - name: debug role path
  #     debug:
  #       msg: "{{ lookup('env','roles_path') }}"
  roles:
    - role: docker_installation
