---
name: ansible-lint

on:
  push:
    branches: [main]

defaults:
  run:
    shell: bash
    working-directory: ./ansible

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Ansible Lint
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible-lint

      - name: Install Ansible collections
        run: ansible-galaxy collection install -r requirements.yml

      - name: Run YAML Lint
        run: yamllint -c .yamllint .

      - name: Create vault password file
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > .vault_pass
          chmod 600 .vault_pass

      - name: Run Ansible Lint
        env:
          ANSIBLE_VAULT_PASSWORD_FILE: .vault_pass
        run: ansible-lint
